name: CI

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main

concurrency:
  group: ci-${{ github.head_ref || github.ref_name }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: checkout repository
        uses: actions/checkout@v4

      - name: install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          version: "latest"

      - name: setup python
        run: uv python install 3.12

      - name: install dependencies
        run: uv sync --dev --locked

      - name: run tests
        run: uv run pytest
